# Configuration file for InfinitumEconomy plugin, written in UTF-8 format
# Config version, please do not change
ConfigVersion: 1.0

# Ways to storage data
# JSON | SQLITE

DataStorageType: SQLITE

EnableMultipleCurrency: true
EnableBanksAndVaults: true